### ISSUE TITLE
Improve DNS config for email

### ISSUE THREAD

**Issue by Synchro** [EnMarche/en-marche.fr#1100]
This is a deployment issue rather than anything in this repo, but I'm assuming the two are closely related!

The en-marche.fr SPF config in DNS has one major issue and a couple of small ones.

The big issue is that the domain publishes both `TXT` and `SPF` record types, and they also contain different values. The SPF record type [is now deprecated](https://tools.ietf.org/html/rfc7208#section-3.1), and there is very little support for it anyway, so it should simply be removed. This is the offending record, which is also far too permissive:

    en-marche.fr.		300	IN	SPF	"v=spf1 include:spf.mailjet.com ?all"

The TXT SPF record currently contains this:

    v=spf1 include:spf.mailjet.com ip4:95.128.44.0/28 ip4:62.210.35.0/24 ip4:217.70.176.0/20 ip4:195.154.172.245 ip4:62.210.131.196 ip6:2001:4b98:c::/48 include:spf.protection.outlook.com include:spf.mandrillapp.com -all

This is ok, but it's considered polite to put explicit IP addresses first as it saves DNS lookups by receivers, like this:

    v=spf1 ip4:95.128.44.0/28 ip4:62.210.35.0/24 ip4:217.70.176.0/20 ip4:195.154.172.245 ip4:62.210.131.196 ip6:2001:4b98:c::/48 include:spf.mailjet.com include:spf.protection.outlook.com include:spf.mandrillapp.com -all

The `-all` default SPF action and lack of a `_dmarc` record tells me that you're not using DMARC, and so you won't receive notifications if anyone starts forging emails from the en-marche.fr domain. Most mail servers that check SPF will reject a message immediately if it has a `-all` action, which does not give it an opportunity to perform DKIM checks and DMARC policy, so you usually need to use `~all` if you want DMARC to work. I see that you have DKIM set up for mailjet (`mailjet._domainkey.en-marche.fr`). Mandrill (in your SPF list) offers [DKIM signing](https://mandrill.zendesk.com/hc/en-us/articles/205582267-About-SPF-and-DKIM) too, so I'd recommend following that up if you're using it. DKIM signatures are vital when trying to prove the provenance and integrity of emails retrospectively, something that has proved important in some recent political campaigns...

**Comment by tgalopin** [comment]
Hello @Synchro 

I did not answer on this issue and I am sorry to have forgotten (the speed f the campaign did not help :) ). We implemented your recommendations, thanks a lot for your great help!

Do you think you could have a look at the new configuration, to see if we could further improve it?

Thanks!

**Comment by Synchro** [comment]
Sorry, I forgot about this.

I can see you've removed the SPF-type record and re-ordered the SPF TXT record and switched to a `~all` default action. You also have a `_dmarc` record with a `p=none` policy and a reporting address, so that's all good and you should get to hear about some forgery attempts.

The next step would be to implement DKIM signing for all mail sources; this would allow you to change to a `p=reject` policy (as Yahoo, office365, AOL and others do), which would remove other sources of forgery and dramatically increase trust in the provenance and integrity of messages. This is quite difficult to do as it means you have to ensure that _everyone_ using en-marche.fr addresses **must** go through a mail server that can perform the signing, and this may be blocked by some less-enlightened ISPs, probably requiring a VPN as a workaround.

Your previous SPF config had a `-all` default action, which as I mentioned means that DMARC doesn't get to work, but now you have changed to `~all` you could possibly switch to a `p=reject` DMARC policy, making it act just like `-all`, but with the benefit of DMARC reporting. That is, `-all` is roughly equivalent to `~all + p=reject`.
Because you're (mostly) not signing with DKIM, the DMARC decision rests only on SPF. SPF alone can have problems with forwarding (see [this article](https://dmarc.org/2017/03/can-i-use-dmarc-if-i-have-only-deployed-spf/)), but since you were previously happy with a `-all` action that was subject to this anyway, I doubt it would be any different. The safe thing to do is wait for a while and see what info you get from the reports, and if they show any unforwarded forgeries, change policy to `reject`.

FWIW, if I was running a political party I'd probably consider the trust and integrity issue to be more important than accommodating ISP misconfigurations for en-marche.fr users.

BTW, did you see I met some of your colleagues at the Dutch PHP conference last month?

**Comment by tgalopin** [comment]
Thanks for the reply, we are going to work on this :) .

Yes, you met Hadrien, he talked to me about you :) . Thanks for your help and support!
