### ISSUE TITLE
Cookies are not marked as secure

### ISSUE THREAD

**Issue by Synchro** [EnMarche/en-marche.fr#1101]
While the site is served over HTTPS, the two cookies it sets (`enmarche` and `_cfduid`) do not have the `secure` flag set, so attackers may be able to obtain their values and hijack user sessions. They do have the `httpOnly` flag set, preventing scripts from accessing them.

![screen shot 2017-05-09 at 21 27 27](https://cloud.githubusercontent.com/assets/81561/25868904/9d075bac-34fe-11e7-8621-b1d6e71ed5f5.png)

I'm not sure how you're serving things - this repo has no references to secure web serving though you're obviously doing it, and it looks like CloudFlare is handling requests.

For bonus points, you could also set [the `SameSite` flag](https://tools.ietf.org/html/draft-west-first-party-cookies-07) which adds some robust anti-CSRF defence. It's not yet supported by PHP's own cookies, so you would need some other cookie management system that does (like [this](https://github.com/delight-im/PHP-Cookie)).

**Comment by tgalopin** [comment]
Indeed, we are using Cloudfare to serve SSL. I'll have a look at this, thanks!

**Comment by Odusanya18** [comment]
The secure flag could be set by setting cookie_secure under session:cookie_secure  in config.yml. Reference https://symfony.com/doc/3.4/reference/configuration/framework.html#cookie-secure
