### ISSUE TITLE
Des images ne s'affichent pas sur la homepage

### ISSUE THREAD

**Issue by apflieger** [EnMarche/en-marche.fr#1104]
Top de voir ce site en open source !

* firefox : ca s'affiche bien
* chrome : les blocks sont noir, les images ne s'affichent pas.

**Comment by tgalopin** [comment]
Pourriez-vous ouvrir la console développeur de chrome (clique droit > inspecter > console), recharger la page et me coller ici le problème que vous avez ? Je pense que ca doit être lié à un adblocker.

**Comment by apflieger** [comment]
effectivement c'est ad block

GET https://en-marche.fr/css/cookieconsent.min.css net::ERR_BLOCKED_BY_CLIENT

GET https://en-marche.fr/js/cookieconsent.min.js net::ERR_BLOCKED_BY_CLIENT

Uncaught (in promise) ReferenceError: cookieconsent is not defined
    at t.default (https://en-marche.fr/built/52d016550bc2af8bd1fe.0.js:1:112038)
    at https://en-marche.fr/built/52d016550bc2af8bd1fe.0.js:1:953
    at Array.forEach (native)
    at e.value (https://en-marche.fr/built/52d016550bc2af8bd1fe.0.js:1:933)
    at a (https://en-marche.fr/built/940e291826c1fa18ece4.kernel.js:1:8005)
    at https://en-marche.fr/built/940e291826c1fa18ece4.kernel.js:1:8214

**Comment by tgalopin** [comment]
Yes, je dois corriger ca, c'est un bug connu. Merci :) !

**Comment by Marvin-Silva** [comment]
J'ai le même problème avec ma photo de profil, toutefois je ne pense pas que ça soit l'adblock, puisque je ne l'ai pas installé sur mon pc.

**Comment by Marvin-Silva** [comment]
Okay, j'ai viens de résoudre le problème! 

sur mon html avait l'extension jpg , pendant que sur mon fichier avait l'extension JPG. 👍🏼
