### ISSUE TITLE
Slack link in documentation

### ISSUE THREAD

**Issue by Vialonyx** [EnMarche/en-marche.fr#1135]
Hi,
Slack's team URL given on [CONTRIBUTING.MD](https://github.com/EnMarche/en-marche.fr/blob/master/CONTRIBUTING.md) seems not work.
Maybe this access has been privatized, in this case it should be deleted from documentation.

**Comment by tgalopin** [comment]
Indeed, thanks for the notice, it should be removed. Do you want to do a PR?

**Comment by Vialonyx** [comment]
Well, let's do that.

**Comment by Vialonyx** [comment]
#1136
