### ISSUE TITLE
Problème d'encoding lors de l'adhésion

### ISSUE THREAD

**Issue by ldubost** [EnMarche/en-marche.fr#115]
Si tu utilises un caractère "'" dans une adresse lors de l'adhésion et que la page se recharger pour cause de mot de passe trop court (ou autre), alors l'apostrophe est mal encodé:

Par exemple:

```
12 Rue de l'été
```

devient

```
12 Rue de l&#039;été
```

**Comment by YaniOz** [comment]
Bonjour, je ne rencontre pas le même problème. Pour moi "12 Rue de l'été" reste bien "12 Rue de l'été" . après rechargement de la page pour cause de formulaire non valide.
