### ISSUE TITLE
Projet lent avec Docker for Mac

### ISSUE THREAD

**Issue by Walkoss** [EnMarche/en-marche.fr#1180]
J'ai récemment installé le projet en-marche.fr sur mon mac à l'aide du guide mais je fais face à un problème de lenteur sur le site. La homepage peut mettre 30secondes avant de s'afficher et ce même avec le cache. J'avais déjà eu un problème similaire avec un autre projet Symfony que j'ai réglé en partageant par NFS l'application.
Une [issue](https://forums.docker.com/t/how-to-speed-up-shared-folders/9322/6) est ouverte depuis longtemps pour régler ce problème sans succès.

Avez-vous déjà eu ce problème sur mac et comment l'avez vous résolu ?

Docker version: Docker 17.03.1-ce-mac12

**Comment by tgalopin** [comment]
Je n'utilise pas mac personnellement (je suis plutôt Linux) mais je crois que Docker for Mac améliorait ce point là. Est-ce que vous utilisez docker-machine ? Si oui, pourriez-vous tester avec Docker for Mac ?

**Comment by Walkoss** [comment]
J'utilise Docker for Mac. J'ai également testé avec docker-machine sans résultat.

**Comment by tony-tran** [comment]
J'utilise docker-machine avec `docker-machine-nfs` aucune lenteur de mon côté.

**Comment by Walkoss** [comment]
@tony-tran J'ai installer `docker-machine` et `docker-machine-nfs` mais je reste à 3 secondes pour la homepage. Quel dossier avez-vous monté avec nfs ?

**Comment by mykiwi** [comment]
Je n'avais pas eu de probleme avec docker & mac.  
Voici ma configuration:

```
docker-machine create \
    --driver virtualbox \
    --virtualbox-memory 3072 \
    --virtualbox-disk-size 40000 \
    docker

brew install docker-machine-nfs
docker-machine-nfs docker --shared-folder=/Users
```

**Comment by Walkoss** [comment]
Merci @tony-tran et @mykiwi !
Problème réglé avec `docker-machine-nfs`
