### ISSUE TITLE
ETQ que visiteur anonyme, je veux pouvoir m'abonner à la newsletter

### ISSUE THREAD

**Issue by tgalopin** [EnMarche/en-marche.fr#12]
- [x] Créer une entité NewsletterSubscription (un champ email et un UUID v5 à partir de ce mail)
- [x] Créer le formulaire (un champ email simple)
- [x] Enregistrer l'inscription dans la BDD
- [ ] Enregistrer le contact dans le CRM
- [ ] Tests automatisés

**Comment by atamano** [comment]
je veux bien prendre cette tache !
