### ISSUE TITLE
ETQ que visiteur anonyme, je veux pouvoir partager une page du site internet sur les réseaux sociaux

### ISSUE THREAD

**Issue by tgalopin** [EnMarche/en-marche.fr#13]
- [ ] Intégrer toutes les balises OpenGraph/Twitter/Facebook/... nécessaires sur toutes les pages et adaptées par type de contenu
- [ ] Intégrer les liens de partages sociaux aux endroits importants

**Comment by marineb** [comment]
On peut fermer ca? C'est fait pour la home et les articles, maintenant il suffit de copier le module sur les nouvelles pages.

**Comment by tgalopin** [comment]
Yes, thx :) !

**Comment by tgalopin** [comment]
Ah oui non, ca inclus aussi toutes les balises Open Graph et compagnie. Faut qu'on finalise ca avant de close cette issue.
