### ISSUE TITLE
[UX][Easy pick] Error message not displayed properly

### ISSUE THREAD

**Issue by xavismeh** [EnMarche/en-marche.fr#1396]
When filling the form on https://en-marche.fr/espace-adherent/mon-profil/synthesis, if the form field `professional_synopsis` is filled with 300+ chars, the error is being displayed on the top of the page when it should be displayed on the field itself.

Nice to have: a chars counter!

**Comment by Neileruaa** [comment]
Hi there ! 

Can I contribute and help on this issue ? Is it still required and useful if I do that ?
I think that's a good way to start contributing :) 

Cheers !
