### ISSUE TITLE
problème connexion Data base 

### ISSUE THREAD

**Issue by devDzign** [EnMarche/en-marche.fr#1425]
Bonjour ma base n'arrive pas a ce charger avec make db , j'ai cette erreur 

make db
docker-compose run --rm app php -r "for(;;){if(@fsockopen('db',3306)){break;}}" # Wait for MySQL

Starting enmarchefr_redis_1 ... done
docker-compose run --rm app bin/console doctrine:database:drop --force --if-exists

Starting enmarchefr_db_1 ... doneone
/usr/bin/env: ‘php\r’: No such file or directory
make: *** [db] Erreur 127

je vous remercie d'avance de votre aide

**Comment by HeahDude** [comment]
Bonjour @devDzign, as-tu bien lancé la commande :
```sh
cp docker-compose.override.yml.dist docker-compose.override.yml
```
?
As-tu changé son contenu?

**Comment by devDzign** [comment]
bonjour 
oui sa déjà fait

**Comment by marineb** [comment]
@devDzign avez vous reussi a la charger?

**Comment by hhamon** [comment]
Le ticket est ouvert depuis presque 6 mois, il peut être fermé je pense n'ayant pas de nouvelles de @devDzign. (cc @tgalopin)

**Comment by tgalopin** [comment]
En effet, si le problème réapparaît n'hésitez pas à ouvrir un nouveau ticket.
