### ISSUE TITLE
port 8000

### ISSUE THREAD

**Issue by cbacelar** [EnMarche/en-marche.fr#1433]
hi,

i only get "http://enmarche.dev:8000/admin" if I put the port in "docker-compose.yml" (and this rule isn't:

    version: "2"
    
    services:
        app:
            build:
                context: docker/dev
            depends_on:
                - db
                - redis
            volumes:
                - .:/app
                - /app/var/cache
                - /app/var/sessions
            ports:
                - "8000:80"
    
        db:
            image: mysql:5.7
            environment:
                MYSQL_ROOT_PASSWORD: root
    
        redis:
            image: redis:3.2
    
        rabbitmq:
            image: rabbitmq:3-management

Am I doing something wrong in some step? or this is the correct way?

thanks so much and sorry for the newbie question!

**Comment by marineb** [comment]
Hi @cbacelar! No, you shouldn't have to do that. Where are you getting stuck? What error are you getting?

**Comment by cbacelar** [comment]
I did:

    clone project
    make start
    put ENMARCHE_DOMAIN into 'parameters.yml'

So:

In http://enmarche.dev/ I get "It works" page
In http://enmarche.dev:8000 I get 'ERR_CONNECTION_REFUSED' in chrome

Thanks!

**Comment by marineb** [comment]
@cbacelar Were you able to get it to work?

**Comment by cbacelar** [comment]
@marineb yes, I had not renamed "docker-compose.override.yml.dist". Sorry!

**Comment by marineb** [comment]
Awesome @cbacelar! 👍
