### ISSUE TITLE
When adding an event to my calendar, if a `#` is found in its title, it strips part of the title of the event

### ISSUE THREAD

**Issue by marineb** [EnMarche/en-marche.fr#1507]
<img width="836" alt="capture d ecran 2017-09-06 15 52 48" src="https://user-images.githubusercontent.com/234208/30217883-7c12dcc8-9485-11e7-8988-9d4685630fd3.png">
<img width="685" alt="capture d ecran 2017-09-06 15 53 09" src="https://user-images.githubusercontent.com/234208/30217885-7dbadc88-9485-11e7-81df-b9a828a4c568.png">

**Comment by anthonykgross** [comment]
Ok guys, I'm on this one !

**Comment by marineb** [comment]
Awesome @anthonykgross!
