### ISSUE TITLE
Notifications par email désactivées par erreur pour de nombreux adhérents ?

### ISSUE THREAD

**Issue by ngrilly** [EnMarche/en-marche.fr#2397]
Nous sommes plusieurs animateurs à constater que de nombreux adhérents se plaignent de ne plus recevoir les emails de leur référent et/ou de leurs animateurs.

Les adhérents que j'ai pu interroger ne se souviennent pas avoir décoché les cases "Emails de vos référents" et "Email de votre animateur local" dans la page Paramètres > [Notifications](https://en-marche.fr/parametres/mon-compte/preferences-des-emails).

J'ai par exemple demandé à François B., adhérent du comité n°1024 "En Marche La Rochelle Centre Les Minimes", de vérifier si les cases en question étaient cochées ou pas. Elles n'étaient pas cochées, et il n'a aucun souvenir de les avoir décochées lui-même.

J'ai cru comprendre que le problème pourrait venir d'un défaut dans la migration de données lors du passage de l'ancien ou nouveau site en-marche.fr, et que les paramètres de notification auraient été écrasés à cette occasion.

Trois questions : 

- Avez-vous connaissance de ce problème ?
- Est-il possible de mesurer l'étendue des dégâts, par exemple en ajoutant une colonne "Notifications" sur la page "Gérer les adhérents" de chaque comité, qui permettrait de savoir si les adhérents ont activé ou désactivé les notifications ?
- Si il y a vraiment eu un défaut dans la migration, est-il possible de corriger les données rétroactivement ? Ou à défaut renvoyer un email aux adhérents leur rappelant de revoir leurs paramètres avec par exemple un bouton "Réactiver les notifications" ?

**Comment by marineb** [comment]
Bonjour Nicolas, n'hésites pas a faire part de ce genre de problème a ton referent qui peut nous remonter cette info, ou bien tu sais nous trouver sur Slack aussi. 

Les personnes qui sont "décochées" sont des personnes qui se sont décochées d'elles-même en cliquant sur le bouton "Se désinscrire" dans les e-mails de leur référents. 

La migration au nouveau site en marche a eu lieu en mars 2017. Donc il y a pas mal de temps. 

Quoi qu'il en soit, nous effectuons des changements actuellement au niveau des notifications (simplification) et nous comptons en effet envoyer un e-mail à tous les adhérents pour leur présenter cette page où ils peuvent gérer leur notifications. 

Je ferme cette issue puisqu'il n'y a pas de problème technique de notre coté. Merci !

**Comment by ngrilly** [comment]
Bonjour Marine,

J'ai également transmis ce message au référent de mon département ;-)

J'ai essayé de me reconnecter au groupe Slack, mais je n'ai pas réussi à retrouver l'URL du groupe : peux-tu me la redonner ?

Sur le fond du problème, je suis un peu étonné car j'ai rencontré beaucoup d'adhérents qui ne reçoivent plus d'emails et ne se souviennent pas s'être désabonnés, ni sur en-marche.fr, ni en cliquant sur le lien de désabonnement dans le footer des emails.

Penses-tu qu'il serait possible d'ajouter une colonne "Notifications email" sur la page "Gérer les adhérents" de chaque comité ?

**Comment by marineb** [comment]
Très bonne idée pour ajouter une colonne notifications e-mail. Ce serait top si tu soumettais une PR pour ca !
