### ISSUE TITLE
Clarification UUID

### ISSUE THREAD

**Issue by Insomniak313** [EnMarche/en-marche.fr#2537]
Bonjour,

Tout d'abord merci de votre code qui est, pour ma part, une référence solide dans l'apprentissage avancé de Symfony. J'aurais besoin d'une clarifiation de votre part : si j'ai bien compris, les UUID sont la solution au problème des séquences sur les bases de données "clusterisées". Mais comment fonctionne la récupération des données ? La même requete est elle faite sur chaque base de données ? Avez vous un serveur intermédiaire pour faire ce type de traitement ? Je me permet de vous demander ça car je ne trouve aucune information à ce sujet et j'ai vu que vous utilisiez les UUID.

En vous remerciant pour votre temps,

Cordialement

Adrien

**Comment by Remg** [comment]
Bonjour,

Sur le projet En Marche nous utilisons les UUID en premier lieu pour identifier une même ressource au sein de différentes applications.
Nous répliquons plusieurs entités (nos utilisateurs, comités, événements etc) vers d'autres applications à la moindre mise à jour. Nous répliquons ces entités avec leurs UUID pour savoir quel ressource mettre à jour sur l'application cible.

Je te conseille de lire cet article qui apporte plus d'éléments de réponse vis à vis des bases de données segmentées (qui n'est pas notre usecase sur En Marche) :
https://tomharrisonjr.com/uuid-or-guid-as-primary-keys-be-careful-7b2aa3dcb439
(merci @B-Galati pour l'article)

N'hésitez pas si vous avez besoin de plus d'infos, on essaiera d'y répondre !

Cordialement,

Rémi
