### ISSUE TITLE
RabbitMqContext method getMessages

### ISSUE THREAD

**Issue by skigun** [EnMarche/en-marche.fr#2559]
Bonjour,

La méthode `getMessages` du [RabbitMqContext](https://github.com/EnMarche/en-marche.fr/blob/master/features/bootstrap/RabbitMqContext.php#L148) consomme tous les messages récupérés.

Un scénario comme celui-ci est toujours vrai, même si le message n'a pas du tout été consommé:
```feature
    When "queue_name" should have 1 message
     And "queue_name" should have message below:
      | body | {"payload"} |
     # other steps
     And "queue_name" should have 0 message
```

Je sais que cette méthode est plutot faite pour le debug. Mais elle s'avère très pratique et comme elle n'est pas documenté. Soit je propose un fix que j'ai déjà fais, soit pourquoi ne pas la documenter ?

**Comment by Remg** [comment]
Bonsoir,

Effectivement on peut améliorer ça.
Si tu as un fix prêt, fais une PR ce sera accueilli avec grand plaisir!
