### ISSUE TITLE
ETQ adhérent / animateur local, je peux proposer des modifications simples du site Internet

### ISSUE THREAD

**Issue by ya35** [EnMarche/en-marche.fr#26]
Les animateurs / trices locaux, ainsi que les membres de leur comité (adhérents), peuvent faire remonter des améliorations, concernant l'outil qu'ils utilisent, tant pour se renseigner sur le mouvement, que pour participer au débat (adhésion / voir ET rejoindre un comité / voir ET rejoindre un événement).

**Voici l'image de la page suggérée (à mettre en lien avec github), accessible depuis le menu du site :**
_Menu actuel :_
![MENU actuel](http://annonyme2.free.fr/enmarche/mod/En-Marche%20-%20menu.png)
_Menu modifié :_
![MENU modifié](http://annonyme2.free.fr/enmarche/mod/En-Marche%20-%20Modification%20-%20ajout%20de%20Contribuer%20dans%20le%20menu.png)
_Page des contributions (à créer et à mettre en lien avec github) :_
![Ajout de la page des modifications souhaitées](http://annonyme2.free.fr/enmarche/mod/En-Marche%20-%20Modification%20-%20ajout%20de%20Contribution.png)

**Comment by ya35** [comment]
Exemple de modification souhaitée :
Dans les documents, mis à dispositions des AL, il est difficile de s'y retrouver : quels documents sont récents, lesquels sont anciens, quels sont ceux que j'ai téléchargés / pas encore vu ?
Merci.

**Comment by tgalopin** [comment]
Hello @ya35 !

Merci de ta proposition :) . Etant donné que le design a été complètement revu (il est en cours d'intégration), tes screenshots ne sont plus vraiment adaptées. En revanche, l'idée d'avoir un moyen de remonter les problèmes et les suggestions est quelque chose sur lequel il faut que nous travaillons.

Nous pensions utiliser Zendesk ou Intercom, mais le choix n'est pas encore fixé. Tu peux venir en discuter sur le Slack :) .

Je ferme cette issue, nous en ouvrerons une plus adaptée une fois la discussion effectuée :) .
