### ISSUE TITLE
Escape the animator message sent to the committee followers

### ISSUE THREAD

**Issue by romain-pierre** [EnMarche/en-marche.fr#289]
I don't know if this is needed but the user story have not provided a behaviour about that.

As a committee animator, when I send a mail message thru the contact form to some followers of my committee, I can put HTML syntax. Also, the content is not `nl2br`.

**Comment by tgalopin** [comment]
This is resolved by https://github.com/EnMarche/en-marche.fr/blob/master/src/AppBundle/Utils/HtmlPurifier.php
