### ISSUE TITLE
Implémenter les Instant Articles Facebook pour les articles

### ISSUE THREAD

**Issue by tgalopin** [EnMarche/en-marche.fr#293]
Utiliser les outils Facebook pour implémenter le système d'Instant Articles à partir des articles du site internet (https://instantarticles.fb.com/).

**Comment by xavismeh** [comment]
# Principe
Pusher du contenu via une API

# Implémentation
1 - utilisation du package composer (officiel) `facebook/facebook-instant-articles-sdk-php` (attention, il y a un composer.lock dans la lib...).
2 - Création d'un token temporaire
3 - Création d'un token permanent (étape 2 obligatoire pour pouvoir le faire)
4 - a) Notification de l'ajout d'un article lors de sa premiere publication (`Facebook\InstantArticles\Client\Client:: importArticle`)
b) Notification de la modification d'un article si publié (`Facebook\InstantArticles\Client\Client:: importArticle` avec `$forceRescrap = true`?)
c) Notification de la suppression d'un article si suppression ou dépublication (`Facebook\InstantArticles\Client\Client:: importArticle::removeArticle` avec l'url absolue de l'article).
