### ISSUE TITLE
Intégrer le design de la page d'accueil

### ISSUE THREAD

**Issue by tgalopin** [EnMarche/en-marche.fr#3]
- [ ] Créer le design fournit en pièce jointe (à venir) en SASS en tenant en compte de l'aspect responsive (en utilisant un framework SASS si besoin)
- [ ] Créer les éléments Javascript et CSS3 nécessaire pour les animations et dynamiques de la page
- [ ] Séparer la page en composants réutilisables en suivant les conventions BEM et OOCSS (http://www.alsacreations.com/article/lire/1641-bonnes-pratiques-en-css-bem-et-oocss.html)
- [ ] Ecrire la documentation liée à l'intégration de cette page (c'est la première page intégrée, il faut donc décrire comment utiliser les composants réutilisables)

Cette issue peut faire l'objet de plusieurs PR plus petites.

**Comment by marineb** [comment]
Je veux bien prendre la premiere tache de cette issue.

**Comment by marineb** [comment]
Notes personnelles:
[ ] Accessibility
