### ISSUE TITLE
Sur page de confirmation d'adhésion, détecter le domaine e-mail et ajouter un bouton si connu

### ISSUE THREAD

**Issue by tgalopin** [EnMarche/en-marche.fr#315]
Sur la page de confirmation, si le domaine de l'e-mail enregistré est connu (Gmail, Outlook, Yahoo, etc.), il serait pratique d'ajouter un bouton pour ouvrir dans un nouvel onglet sa messagerie directement.

**Comment by Vialonyx** [comment]
Je peux m'en occuper.

**Comment by tgalopin** [comment]
Okay, je le note en cours :) . Merci !
