### ISSUE TITLE
En tant qu'animateur je veux pourvoir envoyer un mail aux adhérents habitant différentes villes (Codes Postaux)

### ISSUE THREAD

**Issue by csauvage** [EnMarche/en-marche.fr#33]
La plateforme actuelle force a envoyer un mail pour **chaque** code postal, je veux pouvoir sélectionner plusieurs codes postaux pour envoyer un seul et unique batch d'emails

_Issue remontée par plusieurs ALs (59)_

**Comment by tgalopin** [comment]
Le principe de la nouvelle plateforme ne sera pas basé sur des codes postaux, cela devrait résoudre le soucis :) . Je vous expliquerais tout ca dès que le macro-planning est validé en interne :) !
