### ISSUE TITLE
[Atelier des Idées] - processus à améliorer : prise en compte des contributions

### ISSUE THREAD

**Issue by jege31** [EnMarche/en-marche.fr#3370]
**Atelier des Idées - processus à améliorer : prise en compte des contributions**

__Constat__
Dans le processus de l’atelier des idées, lorsqu’une contribution est soumise au vote, son auteur n’a pas forcément intégré les remarques des autres marcheurs. En particulier, si l’auteur est de mauvaise fois, il peut refuser les remarques qui affaiblissent sa proposition parce qu'elles soulèvent des « risques », « des effets négatifs ou pénalisants pour certains publics ».
Si une proposition soumise aux votes ne contient pas d’éléments contradictoires mais seulement les arguments qui servent les intérêts de son auteur, on trompe les votants. Et on peut se demander à quoi a servi l'étape de contribution.

__Solution 1__
__Permettre aux utilisateurs de voter sur les contributions__
Les contributions deviennent ainsi une partie intégrante de la proposition, au même titre que les textes de l'auteur de la proposition. De ce fait, les contributeurs deviennent des co-auteurs de la proposition et  l'auteur n'est plus que l'initiateur.
Les réponses aux contributions restent, comme actuellement, un moyen d’échanger pour la mise au point de ces contributions.

Les modifications à apporter sont les suivantes:
- Dans la vue d’une proposition finalisée, ne masquer aucune contribution,
- Chaque contribution, fait l’objet d’un vote avec des choix dépendants de la nature de la contribution :
   -	Pour les contributions sur le constat : 
« Je suis : Pas d’accord/Partiellement d’accord/D’accord avec ce constat. »
   - Pour les contributions sur la solution :
« Je trouve cette solution Dangereuse/Risquée/Inutile/Utile »
« Je trouve cette solution Irréalisable/A préciser/Réalisable »
« Je trouve cette solution Classique/Innovante »
   - Pour les contributions aux Exemple :
« Je trouve cet exemple Sans rapport/Pertinent pour cette proposition »
   - Pour les contributions sur les risques
« Je pense que l’occurrence de ce risque est Impossible/Possible/Probable/Certain »
« Je pense que l’occurrence de ce risque serait Catastrophique/Grave/Sans gravité»
   - Pour les contributions sur les impacts (budget, droit, environnement, égalité femmes-hommes) :
« Je pense que cet impact est Impossible/Possible/Probable/Certain »
« Je pense que cet impact serait Catastrophique/Grave/Sans gravité/Positif »
- Les contributions sont modifiables, et formatables grâce à l’éditeur WYSIWYG.

   __Question 1.0__
N'y a t'il pas un risque pour un auteur de voir sa proposition totalement dénaturée par d’autres contributeurs ?
      __Solution 1.0.1__ Ne pas intégrer de co-rédaction sur la partie « Solution » de la proposition. Ca évitera un flou sur ce qui est évalué. On évalue la solution proposée par l’auteur qui a pris en compte, s’il le souhaite, les commentaires des autres contributeurs. Autour de cette solution proposée par l’auteur uniquement, tout le reste (le constat, les conséquences, les risques, etc…) est co-rédigé.

   __Question 1.1__
Dans la vue de l’auteur d’une proposition en cours, les boutons « Approuver »/« Désapprouver » ont-ils encore une raison d’être ?

   __Question 1.2__
Faut-il continuer à faire la distinction entre les textes de l’auteur d’une proposition et les contributions des autres contributeurs ? Oui, si le texte de l’auteur contient une synthèse des différentes contributions. Non, si le texte de l’auteur ne contient qu’une contribution comme les autres.

   __Question 1.3__
Faut-il appliquer les mêmes votes aux textes de l’auteur d’une proposition et aux contributions des autres contributeurs ? Si le texte de l’auteur ne contient qu’une synthèse, pas besoin de vote. Si le texte de l’auteur ne contient qu’une contribution comme les autres, il ne devrait pas être d’une classe particulière, donc question N/A.

**Comment by marineb** [comment]
Merci @JeGeEnMarche. C'est un très bon point !
Une premiere amélioration pourrait être par exemple de permettre aux utilisateurs de voter sur les contributions / commentaires pour leur donner plus de poids. 

N'hésitez pas si vous souhaitez vous plonger dans le code, et soumettre une PR pour cette amélioration.

**Comment by JeGeEnMarche** [comment]
Bonjour @marineb et merci pour cette réponse.

Concernant, votre proposition de solution à cette Issue, j’ai essayé d’imaginer plus en détail comment la réaliser (voir + haut). Je pense qu’il faut la mûrir encore. J’attends vos retours.
	
Concernant ma participation au codage, ce sera avec plaisir. Le plus dur sera évidemment de commencer. Je compte m’y mettre dans les jours ou les semaines qui viennent. Pourrai-je avoir du support en cas de difficulté ?
