### ISSUE TITLE
Améliorer le SEO et l'accessibilité

### ISSUE THREAD

**Issue by tgalopin** [EnMarche/en-marche.fr#350]
Il y a un gros travail d'accessibilité et de SEO à réaliser. Les points urgents sont:

- [ ] Créer un sitemap dynamique
- [ ] Ajouter des attributs lang sur le HTML
- [ ] Ajouter des alt sur toutes les images
- [ ] Mettre en place https://www.google.com/webmasters/tools/home?hl=fr
- [ ] Il y a plusieurs balises H1 sur plusieurs pages, il faut supprimer ce duplicata
- [ ] (ajouter tout ce qui peut améliorer le SEO)

**Comment by AvenirNumerique** [comment]
le searchconsole est-il en place ? Sitemap, statique dynamique ?

**Comment by AvenirNumerique** [comment]
les fichiers robots sont en places ?

**Comment by anjismail** [comment]
Il faudra faire un gros travail SEO dès que le programme sera en ligne. 
Mais en attendant, on peut déjà optimiser les pages des meetings: 
exemple: 
https://en-marche.fr/article/meeting-macron-porte-de-versailles-discours (301 sur la 
sujet: **"travail"**
Propositions de Reco (modèle à suivre pour les autres pages)
URL: https://en-marche.fr/article/macron-travail-versailles
H1: Les propositions d'Emmanuel Macron sur le Travail
H2: Retrouvez l'ensemble du discours du 10 Mars 2016 à Versailles sur la thématique du Travail
Alt Img: propositions travail emmanuel macron

**ACTUALITÉS**
Selon le rythme de publication, ce "blog" sera un vrai atout, donc il faut optimiser les articles et les titres. 
Propositions de reco pour https://en-marche.fr/article/emmanuel-macron-rencontre-causette
URL: https://en-marche.fr/article/macron-egalite-homme-femme
H1: L'égalité Homme / Femme vue par Emmanuel Macron
Alt img: emmanuel macron égalité homme femme


**COUPLE MACRON**
Volume de recherche important autour du couple, Emmanuel Macron & Brigitte Trogneux. 
![capture d ecran 2017-02-17 a 13 01 30](https://cloud.githubusercontent.com/assets/1291343/23064623/56f2ab8a-f511-11e6-9a37-0cd0a9a3100a.png)
La page qui doit remonter sur ces requêtes doit être: https://en-marche.fr/emmanuel-macron (pour éviter que les internautes arrivent sur les sites people ou médisants) 
Il y a deux possibilités pour ce faire:
1. on optimise la page  (les balises ne sont pas au top, le champ sémantique non plus) et on la pousse avec des liens intra-site (mais il semble que cette page soit signée, donc peut on faire des modifs?)
2. on créé une autre page, style wikipédia, avec une biographie un peu plus complète sur EM et BT. 
PS: au sujet de Wikipédia, il faudrait surveiller les modifications apportées dessus car il y a plusieurs paragraphes assez négatifs, et pas certains que les contributeurs derrières soient neutres...
