### ISSUE TITLE
problème affichage mobile bas de la home

### ISSUE THREAD

**Issue by AvenirNumerique** [EnMarche/en-marche.fr#380]
Sur iphone 5 j'ai ce résultat, sur le simulateur Chrome en 6plus c'est pire mais je peux pas faire un vrai contrôle.
![image1](https://cloud.githubusercontent.com/assets/24246863/23114653/995c0670-f740-11e6-9b3e-2ff71270a08e.PNG)

**Comment by tgalopin** [comment]
C'est parce que tu dois pouvoir scroller horizontalement. Si tu peux pas, c'est un bug

**Comment by AvenirNumerique** [comment]
effectivement, mais pour le coup c'est pas clair.
je n'avais pas compris/vu que l'on pouvais le faire.
