### ISSUE TITLE
API for citizen_projects

### ISSUE THREAD

**Issue by agebeyaw** [EnMarche/en-marche.fr#3881]
First of all, thank you for this amazing project! 

I was trying to find the implementation of the API related to the `citizen_projects` (like the ones here https://staging-api.en-marche.fr/citizen_projects/categories)

So far, I was not able to find where it is implemented in `en-marche.fr` project. is there any specific configuration i have to make (may be related to `api-platform`) ?

In my local installation,  http://en-marche.code/api/citizen_projects/categories gives me 404.

Thank you!

**Comment by ottaviano** [comment]
Hi @agebeyaw, thank you for your comment :) 
the citizen project and its categories are exposed on API via another project, not by `en-marche.fr` main project. 
That's why you get 404 on `en-marche.code/api/citizen_projects/categories`

**Comment by agebeyaw** [comment]
Hi @ottaviano,

Thanks for your reply. Is that project, too, publicly available?

**Comment by ottaviano** [comment]
@agebeyaw no, this project is private

**Comment by Remg** [comment]
Hi @agebeyaw ,

Like @ottaviano said, the project holding the citizen_projects API is indeed private.
But the endpoints are still public !

You can consume this endpoint (generated with apiplatform):
https://api.en-marche.fr/citizen_projects
(also a swagger should appear with this URL in your browser)


fyi, our citizen projects search on en-marche.fr is using this endpoint.
https://en-marche.fr/projets-citoyens

**Comment by agebeyaw** [comment]
Thank you @Remg and @ottaviano for your replies.
