### ISSUE TITLE
Ajustements de design homepage

### ISSUE THREAD

**Issue by marineb** [EnMarche/en-marche.fr#40]
- [x] Lead stories: les deux stories devraient avoir des sous-titres identiques (roboto, letter-spacing, 14px)
- [x] Lead stories: accorder l'espace entre leur headline et leur sous-titre
- [x] Logo: letter-spacing devrait être à `-0.7px` 
- [x] Le Movement: increase letter-spacing to `2.5px`
- [x] Le Movement: add bottom spacing before the quote
- [x] Navigation: remonter la loupe
- [x] 3 boucliers: l'ombre gradient missing entre la photo et le text (pour faciliter la lecture) 
- [x] Footer: wrap row on tablet
- [x] News: re-élargir a 1200px, et de ce fait, agrandir les cards
- [x] News: En mode tablet, deux stories par ligne, toutes à la meme taille
- [x] Movement modules shouldn't spread
- [x] "3 boucliers pour proteger..." la hauteur change à 350px avec une largeur à 1200px, pas full-weight

**Comment by tgalopin** [comment]
Tu peux fermer ca si c'est ok ?
