### ISSUE TITLE
Ajouter/supprimer des animateurs

### ISSUE THREAD

**Issue by ngrilly** [EnMarche/en-marche.fr#455]
Est-il toujours prévu qu'on puisse ajouter/supprimer des animateurs sur la page "Gérer les adhérents" ?

**Comment by tgalopin** [comment]
Oui tout à fait, ce n'est pas encore possible mais le système est prévu pour et cela devrait arriver sous peu.

**Comment by ngrilly** [comment]
Les commits récents répondent à cette demande puisqu'il est maintenant possible d'ajouter-retirer des co-animateurs. On ferme ce ticket ?

**Comment by hhamon** [comment]
On peut ajouter des co-animateurs mais on ne peut pas en retirer à ma connaissance.

**Comment by hhamon** [comment]
Je n'ai rien dit en fait. Donc à priori ce ticket peut être fermé je pense.

**Comment by tgalopin** [comment]
Yes, j'ai déployé ca hier et ce matin. J'ai implémenté la feature pour supprimer un animateur. Thx @ngrilly et @hhamon !

**Comment by ngrilly** [comment]
Merci @tgalopin !
