### ISSUE TITLE
Pb d'affichage de l'heure d'un évènement

### ISSUE THREAD

**Issue by fmassot** [EnMarche/en-marche.fr#469]
Exemple : un évènement qui a lieu à 20h mais qui est affiché pour 8h

https://en-marche.fr/evenements/6807b962-ae6c-5558-81a5-29f80dee2749/reunion-publique-vers-l-egalite-reelle-femmes-hommes

**Comment by tgalopin** [comment]
Done in https://github.com/EnMarche/en-marche.fr/commit/f7a6720de9453e3f4f70364e4710fead26d30da6
