### ISSUE TITLE
ETQ animateur, voir/exporter la liste des inscrits à un événement

### ISSUE THREAD

**Issue by ngrilly** [EnMarche/en-marche.fr#480]
La version précédente de la plateforme permettait aux animateurs de voir/exporter la liste des inscrits à un événement. Cela n'est plus possible avec la nouvelle plateforme. Or cela était très utile. Est-il prévu de réimplémenter cette fonctionnalité ?

**Comment by tgalopin** [comment]
Oui, tout à fait, je suis en train de travailler sur les bugs et je travaillerais sur cela dès que possible

**Comment by ngrilly** [comment]
Génial ! Merci. Bon courage pour le bug fixing :-)

**Comment by tgalopin** [comment]
Merci :) .

**Comment by ngrilly** [comment]
J'ai l'impression que ça a été implémenté avec le commit 8971fe1714522413453bc98636bd0592622abfbf ? Je vois désormais un onglet "Gérer les participants" sur chaque événement.

**Comment by tgalopin** [comment]
Yes, c'est implémenté :) !

**Comment by ngrilly** [comment]
Merci !
