### ISSUE TITLE
Absence d'email de notification quand un adhérent suit un comité

### ISSUE THREAD

**Issue by ngrilly** [EnMarche/en-marche.fr#503]
Ces derniers jours, depuis le lancement de la nouvelle plateforme, j'ai constaté que 3 nouvelles personnes ont décidé de suivre mon comité, mais je n'ai reçu aucun email de notification.

En revanche, je reçois bien les autres emails, par exemple lorsque j'envoie un message aux adhérents du comité.

**Comment by tgalopin** [comment]
C'était volontaire, car le nombre de personnes suivant un comité peut augmenter rapidement : vous seriez spammés de mails. Penses tu que cela vale tout de même le coup ?

**Comment by ngrilly** [comment]
L'ancienne plateforme envoyait des notifications. Je pense que c'est utile, car ça permet à l'animateur d'accueillir en bonne et due forme le nouvel arrivant. Sinon, la personne risque de se demander pourquoi l'animateur ne la contacte pas. 

Par ailleurs, je pense qu'il est rare de recevoir plus d'une dizaine de nouveaux membres sur un comité par semaine, donc ça reste raisonnable.

Donc à mon avis, ça vaut le coup d'envoyer une notification :-)

**Comment by tgalopin** [comment]
Je vais en discuter, voir si on remet ca en place alors :) . Merci du retour !

**Comment by RonanSauvage** [comment]
Autre proposition, n'adresser qu'un mail à intervalle régulier  (configurable ?) Récapitulant aux animateurs de se tenir informé des news. 

Bien évidemment si aucune News on pourrait ne rien envoyer. En terme de modélisation il suffirait d'enregistrer par le biais d'un event listener en db les évents notables puis de lancer un CRON pour adresser le mail.

**Comment by ngrilly** [comment]
@tgalopin Me confirmes-tu que la plateforme envoie à nouveau des emails de notification ? Je suppose que oui, puisque j'en reçois à nouveau depuis plusieurs semaines.

**Comment by tgalopin** [comment]
@ngrilly yes :)
