### ISSUE TITLE
Indiquer à un animateur qui envoie un email à ses membrer qu'il recevra une copie de son email

### ISSUE THREAD

**Issue by ngrilly** [EnMarche/en-marche.fr#512]
Sur la page "Gérer les adhérents" de mon comité, j'ai sélectionné un adhérent, puis j'ai cliqué sur "Contacter" afin d'envoyer un email à cet adhérent.

La page sur laquelle je rédige mon message indique bien "Votre message sera envoyé par e-mail à 1 adhérent de votre comité".

Je rédige mon message, puis je clique sur "Envoyer".

Etrangement, quelques instants plus tard, j'ai reçu le message en question sur mon adresse email, ce qui est inattendu.

J'ai fait quelques essais en créant un deuxième compte pour adhérer à mon propre comité, et il semble que la plateforme envoie automatiquement une copie du message à l'animateur. Si cela est confirmé, il serait utile de l'indiquer dans l'interface utilisateur :-)

**Comment by tgalopin** [comment]
C'est le cas oui, pour vérifier que le mail a bien été envoyé. Je note la proposition, merci !

**Comment by ngrilly** [comment]
Merci !
