### ISSUE TITLE
Corriger le CSS des listes à puces (<ul> et <li>)

### ISSUE THREAD

**Issue by ngrilly** [EnMarche/en-marche.fr#521]
Le CSS des listes à puces (éléments HTML UL et LI) est remis à zéro.

Par conséquent, les listes à puces sont "invisibles".

Exemple sur cet événement : https://en-marche.fr/evenements/d1c94ea8-dbed-4f24-b9c9-b71c9832da88/2017-03-09-environnement-et-democratie-le-programme-d-emmanuel-macron

La description "A propos" contient une liste à puces qui apparaît comme de simples retours à la ligne.

**Comment by tgalopin** [comment]
En effet ! Crois-tu que tu pourrais le faire dans une PR :) ? Si non, pas de soucis, on le notera dans une tâche.

**Comment by ngrilly** [comment]
Oui, pourquoi pas ! Je peux me jeter à l'eau. Je suis juste un peu refroidi par la lenteur de la procédure d'installation en local. La dernière fois que j'ai essayé (il y a quelques semaines), ça a mouliné pendant au moins 2 heures. Je crois que j'ai supprimé les containers Docker depuis et il faut sans doute que je recommence.

**Comment by tgalopin** [comment]
Ce n'est pas censé être si lent :/ . Si tu es motivé, on a un slack Open-Source, je peux t'y inviter pour en discuter (si t'es motivé, envoie moi un mail à titouan.galopin@en-marche.fr).

**Comment by ngrilly** [comment]
Je t'ai envoyé un email :-)
