### ISSUE TITLE
ETQ animateur, j'aimerais voir les noms de famille, adresses email et numéros de téléphone

### ISSUE THREAD

**Issue by ngrilly** [EnMarche/en-marche.fr#522]
# Le problème

Le siège de En Marche demande aux animateurs d'utiliser la plateforme au maximum, notamment en créant un événement correspondant à chaque action de terrain (kiosque, porte-à-porte, déambulation, boîtage, dîner d'appartement, etc.).

Toutefois, en tant qu'animateur, nous n'avons accès qu'au prénom et au code postal des membres de nos comités et des participants à nos événements (ainsi qu'à l'initiale du nom de famille et à l'âge pour les membres des comités).

Ces informations sont insuffisantes pour organiser nos actions de terrain :

- Elles ne permettent pas de savoir précisément qui participe à une action de terrain (je peux avoir plusieurs "Pierre" parmi les membres et les sympathisants de mon comité).
- Elles ne permettent pas de contacter facilement les participants (j'ignore leur nom de famille, leur adresse email et leur numéro de téléphone).
- Elles ne permettent pas de géolocaliser les membres et les participants sur une carte pour organiser les actions de terrain, car nous n'avons pas l'adresse postale (mais c'est sans doute le point le moins important).

La conséquence de cela, c'est que nous développons **tous** des fichiers et des outils parallèles, alors que la plateforme est superbe et est censée servir à cela.

Lorsque nous gérons une liste de diffusion séparée, nous ne pouvons même pas réaliser un dédoublonnage, puisque nous ignorons qui sont les membres de nos comités. Le résultat est que certains reçoivent nos messages deux fois : une fois via la plateforme en-marche.fr, une autre fois via nos listes de diffusion gérées en parallèle. Cela crée beaucoup de confusion car les gens se demandent pourquoi ils reçoivent deux fois la même information. 

Cela crée aussi de la confusion lorsqu'une personne souhaite se désabonner : Si elle se désabonne via la plateforme en-marche, l'animateur n'a pas l'information et continue à lui envoyer des messages depuis sa liste de diffusion personnelle. Si elle se désabonne auprès de l'animateur, l'animateur n'a aucun moyen de signaler le désabonnement sur la plateforme.

# Les solutions

La solution la plus évidente serait d'ajouter des colonnes "nom de famille", "adresse email", "numéro de téléphone" et, soyons fous, "adresse postale", dans les onglets "Gérer les adhérents" et "Gérer les participants". Je comprends que la CNIL voit cela d'un mauvais oeil, et fait pression pour que nous ne suivions pas cette voie. Je remarque cependant que les responsables de section du PS ont accès au fichier détaillé des membres de leur section. Avec le cadre juridique adéquat (un engagement de confidentialité signé en ligne par chaque animateur, et un texte indiquant clairement à chaque membre/participant que ses coordonnées seront partagées avec l'animateur), on peut donc imaginer que cela serait possible.

Une solution alternative consisterait à indiquer le nom de famille afin de permettre de distinguer chaque membre/participant (le prénom est insuffisant), mais à conserver cachés l'adresse email et le numéro de téléphone. Dans ce cas, il est essentiel que la plateforme permette :

- D'envoyer des emails de façon plus souple (notamment en nous donnant la main sur l'objet de l'email) ;
- D'envoyer des SMS directement depuis la plateforme ;
- D'appeler un membre ou un participant directement depuis la plateforme ;
- De maintenir une liste des sympathisants du comité, séparée de la liste des adhérents du comité, en nous permettant d'importer les contacts collectés pendant nos actions de terrain (l'alternative, pas forcément plus simple, serait de nous permettre d'importer la liste des adresses email de nos sympathisants et nous indiquer les doublons et les désinscriptions).

**Pour nous organiser sur le terrain, nous avons besoin de communiquer par email, SMS et téléphone.** Si la plateforme ne le permet pas, alors nous sommes contraints de développer des outils parallèles, qui viennent "en concurrence" de la plateforme.

Je suis à la disposition de l'équipe pour travailler sur cette question si nécessaire. Je fais de l'analyse de données clients (data mining) depuis plus d'une dizaine d'années et développe également un logiciel de gestion des recrutements ; je suis donc sensibilisé tant aux questions techniques qu'aux questions relatives à la protection des données personnelles.

Je pense qu'il est crucial d'avancer là-dessus. Notre organisation par comités locaux avec la plateforme en-marche.fr est fortement inspirée de l'organisation des campagnes Obama avec les Neighborhood Team Leaders (NTL) et My.BarackObama.com. Mais sans possibilité de communiquer avec leurs membres/participants, nos animateurs de comités locaux n'auront jamais la même efficacité que les NTL de Obama.

Merci !

**Comment by ngrilly** [comment]
?

**Comment by tgalopin** [comment]
@ngrilly J'ai fermé parce que le débat ne peut pas avoir lieu dans la mesure où c'est une mesure imposée par la CNIL. Je préfère ne pas avoir d'issue ouverte qui ne pourra pas être résolue :) .
