### ISSUE TITLE
Améliorer le support des outils pour malvoyants

### ISSUE THREAD

**Issue by tgalopin** [EnMarche/en-marche.fr#556]
Recommandations à mettre en place:
https://docs.google.com/document/d/17ILoTGiHaTIarZhuC4Mhkkm1Hw1XkFhTjz1Ia_0o7Ww/edit?usp=sharing

- [ ] Polices relatives
- [ ] Labeliser la structure
- [ ] Nommer les liens
- [ ] Mettre des alt sur toutes les images
- [ ] Nommer les zones

**Comment by aurelienmorel** [comment]
Il y a de quoi faire : https://references.modernisation.gouv.fr/rgaa-accessibilite/criteres.html
I am working on it !
