### ISSUE TITLE
Le PDF "atelier du programme" est en fait celui du "porte-à-porte"

### ISSUE THREAD

**Issue by ngrilly** [EnMarche/en-marche.fr#558]
Sur la page "Je Marche" (https://en-marche.fr/jemarche), lorsqu'on clique sur "L'atelier du programme", puis "Télécharger le guide de l'action", le PDF obtenu est le même que celui du porte-à-porte : https://storage.googleapis.com/en-marche-prod/je-marche/je-marche-atelier.pdf !

**Comment by tgalopin** [comment]
Merci, on est dessus :) .

**Comment by tgalopin** [comment]
Ca devrait être réglé.

**Comment by ngrilly** [comment]
Oui, je confirme, c'est réglé. Merci !
