### ISSUE TITLE
Fignoler la home

### ISSUE THREAD

**Issue by marineb** [EnMarche/en-marche.fr#59]
- [x] Boutons de partage sur la home
- [x] Refactor les gradients en mixins
- [x] Le petit espace sous la newsletter
- [x] Ajuster les donate boutons dans certaines situations responsives
- [x] Centrer le footer en responsive
- [x] Add smoother horizontal scrolling for le mouvement 
- [ ] Animer la bande de donation
- [ ] Implementer le fixed header

**Comment by tgalopin** [comment]
Done ?

**Comment by marineb** [comment]
Oui on peut fermer et gerer improvements dans trello!
