### ISSUE TITLE
Afficher le nom de famille complet

### ISSUE THREAD

**Issue by ngrilly** [EnMarche/en-marche.fr#668]
Sur la page "Gérer les adhérents" d'un comité, seule l'initiale du nom de famille est visible.

Pourtant, le nom de famille complet d'un membre est visible en cliquant sur le bouton "Définir co-animateur".

Pourrions-nous afficher le nom de famille complet dans la liste des membres du comité ?

**Comment by tgalopin** [comment]
C'était une erreur, en effet, je l'ai corrigé dans le commit https://github.com/EnMarche/en-marche.fr/commit/c597e7c3aadf23259878693b3aa9a71ff708fb55. Je comprend la demande, mais je ne fait qu'appliquer les demandes de la CNIL. Nous nous devons d'être irréprochables sur ce genre de données.

Je ne peux clairement pas prendre la décision moi-même, et en discuter avec la CNIL est compliqué. Vous avez le prénom, l'initial du nom et l'age de la personne pour savoir qui est qui, cela devrait être suffisant pour ne pas vous tromper :) .

**Comment by ngrilly** [comment]
Ok. Je comprends le problème. Est-il possible d'avoir un lien vers un document de la CNIL décrivant les contraintes auxquelles nous sommes soumises, histoire de régler cette question une fois pour toute ? En effet, on parle à chaque fois des "demandes de la CNIL", mais en restant toujours vague sur ce que cela inclut ou pas. Un document formel aiderait à clarifier les choses. 😃

**Comment by tgalopin** [comment]
Le format de notre mouvement est unique, et c'est bien le problème : même la CNIL n'a pas de règles précises. Nous lui posons souvent des questions et travaillions directement avec eux pour éclairer des points spécifiques à En Marche. Il n'y a donc pas de document exhaustif sur tout cela, c'est un travail de tous les instants.

**Comment by Alekzandre** [comment]
Bonne Remarque, nous allons en parler avec nos interlocuteurs CNIL. 
Cependant compte tenu du nombre de sujets que nous devons traiter à ce jour, ce n’est pas prioritaire.
