### ISSUE TITLE
ETQ visiteur, je ne veux pas attendre 10 min le temps que les grandes images chargent

### ISSUE THREAD

**Issue by marineb** [EnMarche/en-marche.fr#70]
Je me demande si on pourrait faire un truc comme cela.
https://jmperezperez.com/medium-image-progressive-loading-placeholder/
https://css-tricks.com/the-blur-up-technique-for-loading-background-images/

Serait-il possible d'obtenir de plus petites images du server @tgalopin? 
J'ai trouvé ca pour re-dimensionner les images: https://github.com/liip/LiipImagineBundle.

**Comment by tgalopin** [comment]
Je vais mettre en place https://github.com/thephpleague/glide, il sera plus adapté, surtout vu qu'on sera sur Google Cloud Storage. Je vais voir ca. Pour le moment, la priorité, c'est le système de gestion de contenu.

**Comment by marineb** [comment]
Ok ca marche!
