### ISSUE TITLE
Simplifier le template utilisé pour les emails envoyés par les animateurs

### ISSUE THREAD

**Issue by ngrilly** [EnMarche/en-marche.fr#716]
J'ai constaté que le template utilisé pour les emails envoyés par les animateurs a récemment été mis à jour, notamment afin d'intégrer la nouvelle identité visuelle En Marche.

J'ai constaté quelques problèmes (illustrés par la copie d'écran ci-dessous):

- L'entourage gris autour du corps de l'email est interrompu au niveau de la signature "A très bientôt, L'équipe d'En Marche !".
- Les formules de politesse au début et à la fin de l'email sont alignées à gauche, tandis que le corps de l'email saisi par l'animateur est centré. -> Dans un souci de cohérence, je propose d'aligner à gauche l'ensemble du texte (sauf les paragraphes que l'animateur aurait volontairement centrés ou alignés à droite dans l'éditeur).
- Le message de l'animateur est entouré d'une marge à gauche et d'une marge à droite très importantes, qui rendent la colonne de texte trop étroite. -> Je propose de retirer les marges gauche et droite. Les filets au-dessus et au-dessous du texte sont sans doute suffisants pour marquer la séparation.
- De façon générale, je constate que beaucoup d'animateurs intègrent leurs propres formules de politesse dans leur message, redondantes des formules de politesse "obligatoires". -> Je propose de retirer le "Bonjour" au début du message, conserver uniquement la formule "Nicolas, animateur(trice) de votre comité, vous envoie ce message :", et supprimer la formule "A très bientôt, L'équipe d'En Marche !" à la fin du message.

Si j'ai bien compris, les templates sont gérés dans Mailjet, et il n'est donc pas possible de proposer une Pull Request 😃 

<img width="934" alt="screen shot 2017-04-01 at 19 08 45" src="https://cloud.githubusercontent.com/assets/594688/24580787/cabeda06-170e-11e7-95d7-e5ae1bc56aa1.png">

**Comment by marineb** [comment]
We've most of these improvements and will make more in the coming months. I'm closing this.

**Comment by ngrilly** [comment]
Ok. Thanks Marine!
