### ISSUE TITLE
Restrictions des routes API

### ISSUE THREAD

**Issue by Piloudev** [EnMarche/en-marche.fr#8537]
A l'heure actuelle, il n'y a pas vraiment de restriction de format d'entrée pour les requêtes (sauf erreur de ma part).

Nous avons uniquement une définition du "_format".
https://github.com/EnMarche/en-marche.fr/blob/master/config/routes.yaml#L108

Mais qui n'est pas utilisé comme dans ce controller par exemple : https://github.com/EnMarche/en-marche.fr/blob/master/src/Controller/Api/CharterController.php

(Ne sachant pas comment fonctionne le paramètre "format" comme dans l'exemple en dessous du texte à cet URL : https://symfony.com/doc/6.3/routing.html#special-parameters
Cela peut aussi être une idée)

L'idée serait d'utiliser les conditions des routes comme dans cet exemple : https://symfony.com/doc/6.3/routing.html#matching-expressions

Exemple :
Route(
        '/aaaa',
        name: 'aaaa',
        condition: "request.headers.get('content-type') === 'application/json",
)]

Etant donné que la condition ne marchera pas si l'on envoie dans un autre format, la route et le controller ne seront pas trouvés et pourront éviter de potentiels problèmes.

J'attends vos retours sur ce point.
Je pourrais faire une PR si vous voulez.

**Comment by Piloudev** [comment]
Cc @tgalopin @ottaviano

**Comment by ottaviano** [comment]
Salut @Piloudev, 

merci pour la volonté de contribuer au projet et félicitation pour ta première issue

C'est vrai que nous n'utilisons pas systématiquement le paramètre `_format` pour chaque controller/action. Ce paramètre est bien utile si le controller sait traiter plusieurs format, par [ce controller](https://github.com/EnMarche/en-marche.fr/blob/81a9d2e65f61807c0059d722c1601b949cebc281/src/Controller/Api/Pap/GetPapCampaignSurveyRepliesController.php#L15) fait un export si le format est csv ou xls et sinon il envoie le contenu en json.

Si cela t'intéresse nous avons qqs idées d'amélioration DX en remplaçant par exemple certaines annotations par les attributs PHP8 ou transformer les fichiers de configuration yaml en fichiers `.php`. Nous n'avons pas eu le temps de créer des issues `help wanted` pour ces sujets..

**Comment by Piloudev** [comment]
D'accord, si tu as des exemples à envoyer, je suis preneur
Juste pour information, ça apportera quoi de tout transformer en fichier .php ?

Quels autres tâches tu aimerais faire pour améliorer le projet ? @ottaviano
