### ISSUE TITLE
Etapes inversées dans la doc d'install

### ISSUE THREAD

**Issue by mdelem** [EnMarche/en-marche.fr#9]
Dans [la doc d'installation](https://github.com/EnMarche/en-marche.fr/blob/master/docs/installation.md) l'étape `2.a` doit avoir été réalisée avant de lancer la commande `php bin/symfony_requirements` de l'étape `1.b` sans quoi une erreur fatale est affichée:

```
php bin/symfony_requirements

Symfony Requirements Checker
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

> PHP is using the following php.ini file:
  /usr/local/etc/php/7.0/php.ini

> Checking Symfony requirements:
  ..E.........................WW......


 [ERROR]
 Your system is not ready to run Symfony projects
```

**Comment by tgalopin** [comment]
En effet, merci, je vais modifier ca.
